# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proto/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13Proto/service.proto\x12\rproto_package\"\x07\n\x05\x45mpty\"2\n\x07Request\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x14\n\x0cuser_message\x18\x02 \x01(\t\"4\n\x08Response\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x15\n\ruser_response\x18\x02 \x01(\t\"/\n\tConnect_2\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x11\n\tuser_name\x18\x02 \x01(\t\"\x1e\n\tConnect_1\x12\x11\n\tuser_name\x18\x01 \x01(\t2\x9b\x02\n\x0eServer_Service\x12J\n\x13Send_Message_to_all\x12\x18.proto_package.Connect_1\x1a\x17.proto_package.Response0\x01\x12>\n\x07\x43onnect\x12\x18.proto_package.Connect_2\x1a\x17.proto_package.Response0\x01\x12?\n\nDisconnect\x12\x18.proto_package.Connect_2\x1a\x17.proto_package.Response\x12<\n\x0cSend_message\x12\x16.proto_package.Request\x1a\x14.proto_package.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Proto.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=38
  _globals['_EMPTY']._serialized_end=45
  _globals['_REQUEST']._serialized_start=47
  _globals['_REQUEST']._serialized_end=97
  _globals['_RESPONSE']._serialized_start=99
  _globals['_RESPONSE']._serialized_end=151
  _globals['_CONNECT_2']._serialized_start=153
  _globals['_CONNECT_2']._serialized_end=200
  _globals['_CONNECT_1']._serialized_start=202
  _globals['_CONNECT_1']._serialized_end=232
  _globals['_SERVER_SERVICE']._serialized_start=235
  _globals['_SERVER_SERVICE']._serialized_end=518
# @@protoc_insertion_point(module_scope)
